### ISSUE TITLE
Usuário do lider do grupo

### ISSUE THREAD

**Issue by nukdown** [fga-verival/2019-2Grupo7#1]
Comentem nessa issue o usuário github do lider do grupo 7, que será responsável por dar privilegio para os demais membros neste repositório.

**Comment by WelisonR** [comment]
Adiciona ao repositório, por favor, @WelisonR

**Comment by nukdown** [comment]
Perfil adicionado como adm @WelisonR , coloque o resto do seu grupo com permissão para publicar no repositorio. Bom trabalho. Algumas dicas para a fase3 do tbl1 se encontram nesse link no forum do moodle caso ajude. 
https://aprender.ead.unb.br/mod/forum/discuss.php?d=205788
